# This is a mods.toml file for the RankRestrictions mod
# The overall format is standard TOML format, v0.5.0
modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT"

[[mods]]
modId="rankrestrictions" #mandatory
version="1.0.0" #mandatory
displayName="FTBRanks Restrictions Addon" #mandatory
credits="FTB Team for creating FTBRanks" #optional
authors="mchivelli" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''An addon for FTBRanks that enforces item, block, and armor restrictions based on player ranks.
Server admins can configure which ranks can use which items, blocks, or armor.'''

[[dependencies.rankrestrictions]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.rankrestrictions]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
    
[[dependencies.rankrestrictions]]
modId="ftbranks"
mandatory=true
versionRange="[1902.1.3,)"
ordering="AFTER"
side="SERVER"